CREATE DATABASE IF NOT EXISTS panaderia;
USE panaderia;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  image VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cliente VARCHAR(255),
  producto VARCHAR(255),
  cantidad INT,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
